import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';

//import theme from '../theme';
import ResponsiveAppBar from './components/AppBar';
import { CssBaseline } from '@mui/material';




export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <CssBaseline/>
      
          <ResponsiveAppBar />
        {/*<ThemeProvider theme={theme}>{children} </ThemeProvider> */} 
        {children} 
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}